<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ServiceSeeder extends Seeder
{
    
    public function run()
    {
        DB::table('services')->insert([
            [
                'name' => 'Медицинский педикюр',
                'eventColor' => fake()->hexColor(), 
                'price' => 55,
                'price_can_change' => true,
                'duration_minutes_min' => 90, 
                'duration_minutes' => 120, 
                'status' => 1,
                'short_description' => 'Процедура направлена на восстановление и профилактику проблем ногтей и кожи.',
                'full_description' => 'Процедура направлена на восстановление и профилактику проблем ногтей и кожи. Выполняется подологом с использованием стерильных инструментов.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Медицинский педикюр «сложный»',
                'eventColor' => fake()->hexColor(), 
                'price' => 65,
                'price_can_change' => true,
                'duration_minutes_min' => null, 
                'duration_minutes' => 120, 
                'status' => 1,
                'short_description' => 'Процедура направлена на восстановление и профилактику проблем ногтей и кожи.',
                'full_description' => 'Процедура направлена на восстановление и профилактику проблем ногтей и кожи. Выполняется подологом с использованием стерильных инструментов.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Классический педикюр',
                'eventColor' => fake()->hexColor(),
                'price' => 50,
                'price_can_change' => false,
                'duration_minutes_min' => 90,
                'duration_minutes' => 120,
                'status' => 1,
                'short_description' => 'Помогает сохранить здоровье и ухоженный вид стоп.',
                'full_description' => 'Помогает сохранить здоровье и ухоженный вид стоп.Что включает?Размягчение кожи Очищение и обработка ногтей Удаление огрубевшей кожиУвлажнение и массаж. Польза: предотвращает трещины, натоптыши, улучшает внешний вид стоп.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Педикюр «Глубокое увлажнение»',
                'eventColor' => fake()->hexColor(),
                'price' => 60,
                'price_can_change' => false,
                'status' => 1,
                'duration_minutes_min' => null,
                'duration_minutes' => 120,
                'short_description' => null,
                'full_description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Педикюр «Эстетика»',
                'eventColor' => fake()->hexColor(),
                'price' => 60,
                'price_can_change' => false,
                'status' => 1,
                'duration_minutes_min' => null,
                'duration_minutes' => 120,
                'short_description' => null,
                'full_description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Коррекция и обработка вросших ногтей',
                'eventColor' => fake()->hexColor(),
                'price' => 20,
                'price_can_change' => true,
                'status' => 1,
                'duration_minutes_min' => 20,
                'duration_minutes' => 60,
                'short_description' => null,
                'full_description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Обработка трещин и натоптышей',
                'eventColor' => fake()->hexColor(),
                'price' => 20,
                'price_can_change' => true,
                'status' => 1,
                'duration_minutes_min' => 30,
                'duration_minutes' => 60,
                'short_description' => null,
                'full_description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Обработка стоп',
                'eventColor' => fake()->hexColor(),
                'price' => 30,
                'price_can_change' => false,
                'status' => 1,
                'duration_minutes_min' => null,
                'duration_minutes' => 60,
                'short_description' => null,
                'full_description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Обработка ногтей',
                'eventColor' => fake()->hexColor(),
                'price' => 30,
                'price_can_change' => false,
                'status' => 1,
                'duration_minutes_min' => null,
                'duration_minutes' => 60,
                'short_description' => null,
                'full_description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Парафинотерапия',
                'eventColor' => fake()->hexColor(),
                'price' => 19,
                'price_can_change' => false,
                'status' => 1,
                'duration_minutes_min' => null,
                'duration_minutes' => 25,
                'short_description' => null,
                'full_description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Парафинотерапия «Комплекс»',
                'eventColor' => fake()->hexColor(),
                'price' => 75,
                'price_can_change' => true,
                'status' => 1,
                'duration_minutes_min' => null,
                'duration_minutes' => 30,
                'short_description' => null,
                'full_description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        
        DB::table('services')->insert([
            [
                'name' => 'СОС-Услуга',
                'eventColor' => fake()->hexColor(),
                'price' => 40,
                'price_can_change' => false,
                'status' => 1,
                'duration_minutes_min' => null,
                'duration_minutes' => 45,
                'short_description' => null,
                'full_description' => null,
                'time_from' => '08:15',
                'time_to' => '09:00',
                'has_fixed_time' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Консультация',
                'eventColor' => fake()->hexColor(),
                'price' => 15,
                'price_can_change' => false,
                'status' => 1,
                'duration_minutes_min' => null,
                'duration_minutes' => 15,
                'short_description' => null,
                'full_description' => null,
                'time_from' => null,
                'time_to' => null,
                'has_fixed_time' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
