@if($chatState['enabled'])
<style>
  .crm-chat-launcher{position:fixed;z-index:1050;right:clamp(1rem,3vw,2rem);bottom:clamp(1rem,3vw,2rem);border:0;border-radius:999px;min-height:3.5rem;padding:.75rem 1.15rem;background:var(--brand-accent,#3874ff);color:#fff;box-shadow:0 .65rem 2rem rgba(0,0,0,.22)}
  .crm-chat-panel{position:fixed;z-index:1051;right:clamp(1rem,3vw,2rem);bottom:clamp(5.25rem,8vw,6.5rem);width:min(24rem,calc(100vw - 2rem));height:min(36rem,calc(100dvh - 7.5rem));background:var(--phoenix-body-bg,#fff);border:1px solid var(--phoenix-border-color,#ddd);border-radius:1rem;box-shadow:0 .8rem 3rem rgba(0,0,0,.24);overflow:hidden;display:none}
  .crm-chat-panel.is-open{display:flex;flex-direction:column}.crm-chat-panel>header{flex:0 0 auto}.crm-chat-conversation{flex:1 1 0;min-height:0;overflow:hidden}.crm-chat-messages{flex:1 1 0;min-height:0;overflow-y:auto;overflow-x:hidden;overscroll-behavior:contain;scrollbar-gutter:stable;padding:1rem;display:flex;flex-direction:column;gap:.75rem}.crm-chat-send,.crm-chat-rating{flex:0 0 auto;background:var(--phoenix-body-bg,#fff)}.crm-chat-message-group{display:flex;flex-direction:column;max-width:86%;flex:0 0 auto}.crm-chat-message-group.staff{align-self:flex-start}.crm-chat-message-group.public{align-self:flex-end}.crm-chat-sender{margin:0 0 .25rem .25rem;font-size:.75rem;font-weight:700;color:var(--phoenix-body-color,#31374a)}.crm-chat-bubble{max-width:100%;padding:.65rem .8rem;border-radius:.8rem;white-space:pre-wrap;overflow-wrap:anywhere}.crm-chat-message-group.staff .crm-chat-bubble{background:var(--phoenix-body-highlight-bg,#eef2f6)}.crm-chat-message-group.public .crm-chat-bubble{background:var(--brand-accent,#3874ff);color:#fff}.crm-chat-system-event{align-self:center;max-width:94%;flex:0 0 auto;padding:.45rem .75rem;border-radius:999px;background:var(--phoenix-body-highlight-bg,#eef2f6);color:var(--phoenix-secondary-color,#6e7891);font-size:.78rem;line-height:1.35;text-align:center;overflow-wrap:anywhere}.crm-chat-stars{display:flex;justify-content:center;gap:.2rem}.crm-chat-star{border:0;background:transparent;color:#d5dae3;font-size:2rem;line-height:1;padding:.15rem;transition:color .15s,transform .15s}.crm-chat-star:hover,.crm-chat-star:focus-visible,.crm-chat-star.is-selected{color:#f5a623;transform:translateY(-1px)}.crm-chat-dot{width:.55rem;height:.55rem;border-radius:50%;display:inline-block;background:#dc3545}.crm-chat-dot.online{background:#25b36a}
  @media(max-width:575.98px){.crm-chat-panel{inset:.5rem .5rem 5rem .5rem;width:auto;height:auto}.crm-chat-launcher{right:.75rem;bottom:.75rem}}
</style>
<button id="crm-chat-launcher" class="crm-chat-launcher d-flex align-items-center gap-2" type="button" aria-expanded="false"><i class="uil uil-comment-alt-message fs-6"></i><span>{{ __('crm.start_chat') }}</span><span id="crm-chat-badge" class="badge rounded-pill bg-danger d-none">0</span></button>
<section id="crm-chat-panel" class="crm-chat-panel" aria-label="{{ $chatState['title'] }}">
  <header class="p-3 border-bottom d-flex justify-content-between align-items-start gap-3"><div><strong class="d-block">{{ $chatState['title'] }}</strong><small class="text-body-secondary"><span class="crm-chat-dot {{ $chatState['online']?'online':'' }} me-1"></span>{{ $chatState['online'] ? __('crm.online'):__('crm.offline') }}@if($chatState['today_start'] && $chatState['today_end']) · {{ __('crm.today_hours',['start'=>$chatState['today_start'],'end'=>$chatState['today_end']]) }}@endif</small></div><button id="crm-chat-close" class="btn btn-sm btn-link text-body p-0" type="button" aria-label="{{ __('crm.close') }}">×</button></header>
  <div id="crm-chat-intro" class="p-3 overflow-auto"><p class="mb-3">{{ $chatState['online'] ? $chatState['welcome_message']:$chatState['offline_message'] }}</p><form id="crm-chat-start" class="d-grid gap-2">@guest('customer')<input class="form-control" name="name" maxlength="190" required placeholder="{{ __('crm.your_name') }}"><input class="form-control" type="email" name="email" maxlength="190" placeholder="{{ __('crm.email') }}"><input class="form-control" name="phone" maxlength="32" placeholder="{{ __('crm.phone') }}">@endguest<textarea class="form-control" name="message" rows="4" maxlength="4000" required placeholder="{{ __('crm.message') }}"></textarea><div id="crm-chat-error" class="text-danger small d-none"></div><button class="btn btn-primary" type="submit">{{ __('crm.begin') }}</button></form></div>
  <div id="crm-chat-conversation" class="crm-chat-conversation d-none flex-column">
    <div id="crm-chat-messages" class="crm-chat-messages"></div>
    <form id="crm-chat-send" class="crm-chat-send p-2 border-top d-flex flex-wrap gap-2"><textarea class="form-control flex-grow-1" name="message" rows="2" maxlength="4000" required placeholder="{{ __('crm.message') }}"></textarea><button class="btn btn-primary" type="submit" aria-label="{{ __('crm.send') }}"><i class="uil uil-message"></i></button><div id="crm-chat-send-error" class="text-danger small w-100 d-none" role="alert"></div></form>
    <div id="crm-chat-rating" class="crm-chat-rating d-none border-top p-3 text-center">
      <div id="crm-chat-rating-prompt"><strong class="d-block">{{ __('crm.rate_conversation') }}</strong><small class="text-body-tertiary">{{ __('crm.rate_conversation_hint') }}</small><div class="crm-chat-stars mt-2">@foreach(range(1,5) as $score)<button class="crm-chat-star" type="button" data-rating="{{ $score }}" aria-label="{{ __('crm.rating_star',['value'=>$score]) }}">★</button>@endforeach</div></div>
      <div id="crm-chat-rating-thanks" class="d-none"><div class="fw-semibold text-success mb-2">{{ __('crm.rating_thanks') }}</div><button id="crm-chat-restart" class="btn btn-outline-primary btn-sm" type="button">{{ __('crm.start_new_chat') }}</button></div>
      <div id="crm-chat-rating-error" class="d-none text-danger small mt-2" role="alert"></div>
    </div>
  </div>
</section>
<script>
document.addEventListener('DOMContentLoaded', () => {
  const storageKey='crm_chat_session_v1', panel=document.getElementById('crm-chat-panel'), launcher=document.getElementById('crm-chat-launcher'), intro=document.getElementById('crm-chat-intro'), conversation=document.getElementById('crm-chat-conversation'), messages=document.getElementById('crm-chat-messages');
  let csrf=document.querySelector('meta[name="csrf-token"]')?.content;
  let session=null,lastId=0,polling=false,sendingMessage=false,unread=0;
  try{session=JSON.parse(localStorage.getItem(storageKey)||'null')}catch(_){localStorage.removeItem(storageKey)}
  const endpoints={create:@js(route('chat.store')),csrf:@js(route('chat.csrf')),show:@js(url('/chat/conversations'))};
  const request=(url,options={})=>fetch(url,{credentials:'same-origin',cache:'no-store',headers:{'Accept':'application/json','Content-Type':'application/json','X-CSRF-TOKEN':csrf,'X-Requested-With':'XMLHttpRequest'},...options});
  const refreshCsrf=async()=>{const response=await fetch(endpoints.csrf,{credentials:'same-origin',cache:'no-store',headers:{'Accept':'application/json','X-Requested-With':'XMLHttpRequest'}});if(!response.ok)return false;csrf=(await response.json()).token;const meta=document.querySelector('meta[name="csrf-token"]');if(meta)meta.content=csrf;return true};
  const mutate=async(url,payload)=>{const send=()=>request(url,{method:'POST',body:JSON.stringify(payload)});let response=await send();if(response.status===419&&await refreshCsrf())response=await send();return response};
  const mode=()=>{intro.classList.toggle('d-none',!!session);conversation.classList.toggle('d-none',!session);conversation.classList.toggle('d-flex',!!session)};
  const scrollToLatest=()=>window.requestAnimationFrame(()=>{messages.scrollTop=messages.scrollHeight});
  const add=message=>{if(document.querySelector(`#crm-chat-messages [data-message-id="${message.id}"]`))return;let element;if(message.kind==='system'||message.sender==='system'){element=document.createElement('div');element.className='crm-chat-system-event';element.textContent=message.body}else{element=document.createElement('div');element.className='crm-chat-message-group '+(message.sender==='staff'?'staff':'public');if(message.sender==='staff'&&message.sender_name){const sender=document.createElement('div');sender.className='crm-chat-sender';sender.textContent=message.sender_name;element.append(sender)}const bubble=document.createElement('div');bubble.className='crm-chat-bubble';bubble.textContent=message.body;element.append(bubble)}element.dataset.messageId=message.id;messages.append(element);lastId=Math.max(lastId,Number(message.id));if(!panel.classList.contains('is-open')&&(message.sender==='staff'||message.sender==='system')){unread++;const badge=document.getElementById('crm-chat-badge');badge.textContent=unread;badge.classList.remove('d-none')}scrollToLatest()};
  const renderState=state=>{const send=document.getElementById('crm-chat-send'),rating=document.getElementById('crm-chat-rating'),prompt=document.getElementById('crm-chat-rating-prompt'),thanks=document.getElementById('crm-chat-rating-thanks');const closed=state.status==='closed';send.classList.toggle('d-none',closed);const showRating=closed&&(state.can_rate||state.rating);rating.classList.toggle('d-none',!showRating);prompt.classList.toggle('d-none',!state.can_rate);thanks.classList.toggle('d-none',!state.rating);if(state.rating)document.querySelectorAll('.crm-chat-star').forEach(star=>star.classList.toggle('is-selected',Number(star.dataset.rating)<=Number(state.rating)))};
  const poll=async()=>{if(!session||polling)return;polling=true;try{const response=await request(`${endpoints.show}/${session.uuid}/poll?after=${lastId}`,{method:'GET',headers:{'Accept':'application/json','X-Chat-Token':session.token,'X-Requested-With':'XMLHttpRequest'}});if(response.status===403||response.status===404){session=null;localStorage.removeItem(storageKey);mode();return}if(response.ok){const payload=await response.json();payload.messages.forEach(add);renderState(payload)}}catch(_){}finally{polling=false}};
  const open=()=>{panel.classList.add('is-open');launcher.setAttribute('aria-expanded','true');unread=0;document.getElementById('crm-chat-badge').classList.add('d-none');mode();scrollToLatest();poll()}; const close=()=>{panel.classList.remove('is-open');launcher.setAttribute('aria-expanded','false')};
  launcher.addEventListener('click',()=>panel.classList.contains('is-open')?close():open());document.getElementById('crm-chat-close').addEventListener('click',close);
  document.getElementById('crm-chat-start').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,button=form.querySelector('button'),error=document.getElementById('crm-chat-error');button.disabled=true;error.classList.add('d-none');const data=Object.fromEntries(new FormData(form));try{const response=await mutate(endpoints.create,data);if(!response.ok){const payload=await response.json().catch(()=>({}));throw new Error(Object.values(payload.errors||{}).flat()[0]||@js(__('crm.contact_required')))}session=await response.json();localStorage.setItem(storageKey,JSON.stringify(session));form.reset();mode();await poll()}catch(exception){error.textContent=exception.message;error.classList.remove('d-none')}finally{button.disabled=false}});
  document.getElementById('crm-chat-send').addEventListener('submit',async event=>{event.preventDefault();if(sendingMessage)return;const form=event.currentTarget,field=form.elements.message,button=form.querySelector('button[type="submit"]'),error=document.getElementById('crm-chat-send-error'),body=field.value.trim();if(!body||!session)return;sendingMessage=true;field.disabled=true;button.disabled=true;error.classList.add('d-none');try{const response=await mutate(`${endpoints.show}/${session.uuid}/messages`,{token:session.token,message:body});if(response.ok){field.value='';await poll()}else{const payload=await response.json().catch(()=>({}));throw new Error(payload.message||@js(__('crm.send_failed')))}}catch(exception){error.textContent=exception.message;error.classList.remove('d-none')}finally{sendingMessage=false;field.disabled=false;button.disabled=false;field.focus()}});
  document.querySelectorAll('.crm-chat-star').forEach(star=>star.addEventListener('click',async()=>{if(!session)return;const error=document.getElementById('crm-chat-rating-error');error.classList.add('d-none');document.querySelectorAll('.crm-chat-star').forEach(button=>button.disabled=true);try{const response=await mutate(`${endpoints.show}/${session.uuid}/rating`,{token:session.token,rating:Number(star.dataset.rating)});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.message||@js(__('crm.rating_failed')));renderState({status:'closed',can_rate:false,rating:payload.rating})}catch(exception){error.textContent=exception.message;error.classList.remove('d-none');document.querySelectorAll('.crm-chat-star').forEach(button=>button.disabled=false)}}));
  document.getElementById('crm-chat-restart').addEventListener('click',async event=>{if(!session)return;const button=event.currentTarget,error=document.getElementById('crm-chat-rating-error');button.disabled=true;error.classList.add('d-none');try{const response=await mutate(`${endpoints.show}/${session.uuid}/restart`,{token:session.token});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.message||@js(__('crm.restart_failed')));session=payload;localStorage.setItem(storageKey,JSON.stringify(session));messages.replaceChildren();lastId=0;renderState({status:'open',can_rate:false,rating:null});scrollToLatest();await poll();document.getElementById('crm-chat-send').elements.message.focus()}catch(exception){error.textContent=exception.message;error.classList.remove('d-none');button.disabled=false}});
  const enterToSend=form=>form?.elements.message?.addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey&&!event.isComposing){event.preventDefault();form.requestSubmit()}});
  enterToSend(document.getElementById('crm-chat-start'));enterToSend(document.getElementById('crm-chat-send'));
  mode();window.setInterval(poll,2500);window.addEventListener('focus',poll);window.addEventListener('online',poll);document.addEventListener('visibilitychange',()=>{if(!document.hidden)poll()});
});
</script>
@endif
