@if($chatState['enabled'])
<style>
  .crm-chat-launcher{position:fixed;z-index:1050;right:clamp(1rem,3vw,2rem);bottom:clamp(1rem,3vw,2rem);border:0;border-radius:999px;min-height:3.5rem;padding:.75rem 1.15rem;background:var(--brand-accent,#3874ff);color:#fff;box-shadow:0 .65rem 2rem rgba(0,0,0,.22)}
  .crm-chat-panel{position:fixed;z-index:1051;right:clamp(1rem,3vw,2rem);bottom:clamp(5.25rem,8vw,6.5rem);width:min(24rem,calc(100vw - 2rem));height:min(36rem,calc(100dvh - 7.5rem));background:var(--phoenix-body-bg,#fff);border:1px solid var(--phoenix-border-color,#ddd);border-radius:1rem;box-shadow:0 .8rem 3rem rgba(0,0,0,.24);overflow:hidden;display:none}
  .crm-chat-panel.is-open{display:flex;flex-direction:column}.crm-chat-messages{flex:1;overflow:auto;padding:1rem;display:flex;flex-direction:column;gap:.75rem}.crm-chat-bubble{max-width:86%;padding:.65rem .8rem;border-radius:.8rem;white-space:pre-wrap;overflow-wrap:anywhere}.crm-chat-bubble.staff{align-self:flex-start;background:var(--phoenix-body-highlight-bg,#eef2f6)}.crm-chat-bubble.public{align-self:flex-end;background:var(--brand-accent,#3874ff);color:#fff}.crm-chat-dot{width:.55rem;height:.55rem;border-radius:50%;display:inline-block;background:#dc3545}.crm-chat-dot.online{background:#25b36a}
  @media(max-width:575.98px){.crm-chat-panel{inset:.5rem .5rem 5rem .5rem;width:auto;height:auto}.crm-chat-launcher{right:.75rem;bottom:.75rem}}
</style>
<button id="crm-chat-launcher" class="crm-chat-launcher d-flex align-items-center gap-2" type="button" aria-expanded="false"><i class="uil uil-comment-alt-message fs-6"></i><span>{{ __('crm.start_chat') }}</span><span id="crm-chat-badge" class="badge rounded-pill bg-danger d-none">0</span></button>
<section id="crm-chat-panel" class="crm-chat-panel" aria-label="{{ $chatState['title'] }}">
  <header class="p-3 border-bottom d-flex justify-content-between align-items-start gap-3"><div><strong class="d-block">{{ $chatState['title'] }}</strong><small class="text-body-secondary"><span class="crm-chat-dot {{ $chatState['online']?'online':'' }} me-1"></span>{{ $chatState['online'] ? __('crm.online'):__('crm.offline') }}@if($chatState['today_start'] && $chatState['today_end']) · {{ __('crm.today_hours',['start'=>$chatState['today_start'],'end'=>$chatState['today_end']]) }}@endif</small></div><button id="crm-chat-close" class="btn btn-sm btn-link text-body p-0" type="button" aria-label="Close">×</button></header>
  <div id="crm-chat-intro" class="p-3 overflow-auto"><p class="mb-3">{{ $chatState['online'] ? $chatState['welcome_message']:$chatState['offline_message'] }}</p><form id="crm-chat-start" class="d-grid gap-2">@guest('customer')<input class="form-control" name="name" maxlength="190" required placeholder="{{ __('crm.your_name') }}"><input class="form-control" type="email" name="email" maxlength="190" placeholder="{{ __('crm.email') }}"><input class="form-control" name="phone" maxlength="32" placeholder="{{ __('crm.phone') }}">@endguest<textarea class="form-control" name="message" rows="4" maxlength="4000" required placeholder="{{ __('crm.message') }}"></textarea><div id="crm-chat-error" class="text-danger small d-none"></div><button class="btn btn-primary" type="submit">{{ __('crm.begin') }}</button></form></div>
  <div id="crm-chat-conversation" class="d-none flex-column flex-grow-1 min-h-0"><div id="crm-chat-messages" class="crm-chat-messages"></div><form id="crm-chat-send" class="p-2 border-top d-flex gap-2"><textarea class="form-control" name="message" rows="2" maxlength="4000" required placeholder="{{ __('crm.message') }}"></textarea><button class="btn btn-primary" type="submit" aria-label="{{ __('crm.send') }}"><i class="uil uil-message"></i></button></form></div>
</section>
<script>
document.addEventListener('DOMContentLoaded', () => {
  const storageKey='crm_chat_session_v1', panel=document.getElementById('crm-chat-panel'), launcher=document.getElementById('crm-chat-launcher'), intro=document.getElementById('crm-chat-intro'), conversation=document.getElementById('crm-chat-conversation'), messages=document.getElementById('crm-chat-messages'), csrf=document.querySelector('meta[name="csrf-token"]')?.content;
  let session=null,lastId=0,polling=false,unread=0;
  try{session=JSON.parse(localStorage.getItem(storageKey)||'null')}catch(_){localStorage.removeItem(storageKey)}
  const endpoints={create:@js(route('chat.store')),show:@js(url('/chat/conversations'))};
  const request=(url,options={})=>fetch(url,{credentials:'same-origin',cache:'no-store',headers:{'Accept':'application/json','Content-Type':'application/json','X-CSRF-TOKEN':csrf,'X-Requested-With':'XMLHttpRequest'},...options});
  const mode=()=>{intro.classList.toggle('d-none',!!session);conversation.classList.toggle('d-none',!session);conversation.classList.toggle('d-flex',!!session)};
  const add=message=>{if(document.querySelector(`#crm-chat-messages [data-message-id="${message.id}"]`))return;const bubble=document.createElement('div');bubble.dataset.messageId=message.id;bubble.className='crm-chat-bubble '+(message.sender==='staff'?'staff':'public');bubble.textContent=message.body;messages.append(bubble);lastId=Math.max(lastId,Number(message.id));if(!panel.classList.contains('is-open')&&message.sender==='staff'){unread++;const badge=document.getElementById('crm-chat-badge');badge.textContent=unread;badge.classList.remove('d-none')}messages.scrollTop=messages.scrollHeight};
  const poll=async()=>{if(!session||polling)return;polling=true;try{const response=await request(`${endpoints.show}/${session.uuid}/poll`,{method:'POST',body:JSON.stringify({token:session.token,after:lastId})});if(response.status===403||response.status===404){session=null;localStorage.removeItem(storageKey);mode();return}if(response.ok)(await response.json()).messages.forEach(add)}catch(_){}finally{polling=false}};
  const open=()=>{panel.classList.add('is-open');launcher.setAttribute('aria-expanded','true');unread=0;document.getElementById('crm-chat-badge').classList.add('d-none');mode();poll()}; const close=()=>{panel.classList.remove('is-open');launcher.setAttribute('aria-expanded','false')};
  launcher.addEventListener('click',()=>panel.classList.contains('is-open')?close():open());document.getElementById('crm-chat-close').addEventListener('click',close);
  document.getElementById('crm-chat-start').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,button=form.querySelector('button'),error=document.getElementById('crm-chat-error');button.disabled=true;error.classList.add('d-none');const data=Object.fromEntries(new FormData(form));try{const response=await request(endpoints.create,{method:'POST',body:JSON.stringify(data)});if(!response.ok){const payload=await response.json().catch(()=>({}));throw new Error(Object.values(payload.errors||{}).flat()[0]||@js(__('crm.contact_required')))}session=await response.json();localStorage.setItem(storageKey,JSON.stringify(session));form.reset();mode();await poll()}catch(exception){error.textContent=exception.message;error.classList.remove('d-none')}finally{button.disabled=false}});
  document.getElementById('crm-chat-send').addEventListener('submit',async event=>{event.preventDefault();const field=event.currentTarget.elements.message,body=field.value.trim();if(!body||!session)return;field.disabled=true;try{const response=await request(`${endpoints.show}/${session.uuid}/messages`,{method:'POST',body:JSON.stringify({token:session.token,message:body})});if(response.ok){field.value='';await poll()}}finally{field.disabled=false;field.focus()}});
  mode();window.setInterval(poll,4000);
});
</script>
@endif
