<?php
return [
    'add_new'=>'Добавить новую запись',
    'personal_calendar'=>'персональный календарь','no_personal_appointments'=>'У этого пользователя пока нет записей. Календарь ниже отображает его личное расписание.','close'=>'Закрыть','select_service'=>'Выберите услугу','select_employee'=>'Выберите сотрудника','surname'=>'Фамилия','appointment_note'=>'Дополнение к записи','save'=>'Сохранить','phone'=>'Телефон',
    'all'=>'Все записи','search'=>'Поиск по клиенту, телефону, email...','all_employees'=>'Все сотрудники','all_services'=>'Все услуги','from'=>'От','to'=>'До','client'=>'Клиент','service'=>'Услуга','employee'=>'Сотрудник','date_time'=>'Дата и время','price'=>'Цена','notes'=>'Заметки','action'=>'Действие','minutes'=>':count мин.','from_price'=>'от','not_found'=>'Записей не найдено','appointments'=>'Записи','service_employee'=>'Услуга / Сотрудник','appointment_time'=>'Время записи','start'=>'Начало','end'=>'Конец','view_all'=>'Показать все','view_less'=>'Показать меньше','today_title'=>'Мои записи сегодня','new'=>'Новая запись','result_needed'=>'Нужно указать результат.','unresolved_count'=>'Завершившихся записей без итогового статуса: :count.','past'=>'прошла','in_progress'=>'идёт сейчас','future'=>'будущая','status_needed'=>'нужен статус','until'=>'до :time','details'=>'Подробнее','result_hint'=>'Услуга закончилась в :time. Отметьте «Завершена» или «Клиент не пришёл».','none_today'=>'Сегодня записей нет','none_today_hint'=>'Новые записи появятся здесь автоматически.','back_all'=>'← Все записи','appointment_number'=>'Запись #:id','details_title'=>'Детали записи','employee_label'=>'Сотрудник','cost'=>'Стоимость','room'=>'Кабинет','not_assigned'=>'Не назначен','comment'=>'Комментарий','no_comment'=>'Комментария нет','about_client'=>'О клиенте','has_account'=>'Есть аккаунт','guest'=>'Гость','snapshot_hint'=>'Контакты сохранены как снимок записи и не меняются вместе с профилем клиента.','recent_client_appointments'=>'Последние записи клиента','open'=>'Открыть','no_other'=>'Других записей не найдено.','message_client'=>'Написать клиенту','subject'=>'Тема','default_subject'=>'Ваша запись на :date','message'=>'Сообщение','recipient'=>'Получатель: :email','send_email'=>'Отправить письмо','no_email'=>'У клиента не указан email.','email_sent'=>'Клиенту отправлено письмо','email_subject'=>'Тема письма','empty'=>'История пока пуста.','recent_client_activity'=>'Последние действия клиента','actions_empty'=>'Действий пока нет.','cancel_prompt'=>'Укажите причину отмены','cancel_failed'=>'Не удалось отменить запись.',
    'cancel' => 'Отменить запись', 'cancel_reason' => 'Причина отмены', 'cancel_reason_help' => 'Причина сохранится в истории записи.',
    'cancel_confirm' => 'Отменить запись от имени компании?', 'cancelled' => 'Запись отменена. Данные и история сохранены.',
    'reason_required' => 'Укажите причину отмены (минимум 3 символа).',
    'history' => 'История записи', 'system' => 'Система', 'reason' => 'Причина', 'empty_history' => 'История изменений пока пуста.',
    'events' => ['history_started' => 'История подключена', 'created' => 'Запись создана', 'updated' => 'Запись изменена', 'status_changed' => 'Статус изменён', 'reschedule_requested' => 'Клиент запросил перенос', 'reschedule_approved' => 'Перенос подтверждён', 'reschedule_rejected' => 'Перенос отклонён'],
    'fields' => ['status' => 'Статус', 'service_id' => 'Услуга', 'user_id' => 'Мастер', 'room_id' => 'Кабинет', 'appointment_start' => 'Начало', 'appointment_end' => 'Окончание', 'price' => 'Цена', 'original_price' => 'Цена до скидки', 'discount_amount' => 'Скидка', 'promo_code' => 'Промокод', 'description' => 'Примечание'],
    'shown' => 'Показано :from–:to из :total', 'masters_today' => 'Записи сотрудников', 'today' => 'Сегодня', 'tomorrow' => 'Завтра', 'yesterday' => 'Вчера', 'day_unavailable' => 'День недоступен', 'non_working_day' => 'Нерабочий день', 'no_appointments' => 'Записей нет', 'calendar' => 'Календарь', 'list' => 'Записи', 'count' => ':count записей', 'minutes_short' => ':count мин.', 'closed_slot_hint' => 'Эта дата недоступна для записи. Закрытое окно редактируется в настройках.', 'image_alt' => 'Изображение', 'delete_log_error' => 'Ошибка при удалении события:', 'time_changed' => 'Время на эту дату изменено', 'future_rule' => 'С :date услуга изменится: :duration мин., :price €', 'select_service_prompt' => 'Пожалуйста, выберите услугу',
    'change_event' => 'Изменить запись',
];
