<?php

return [
    'title'=>'New appointment','subtitle'=>'Find a customer and an available time quickly — all constraints are checked by the server.','back'=>'Back to calendar',
    'service_and_master'=>'1. Service and specialist','service'=>'Service','choose_service'=>'Choose a service','master'=>'Specialist','any_master'=>'Any available specialist','any_master_help'=>'The system shows the earliest times across all specialists and assigns the selected one.','current_master'=>'You','duration'=>':minutes min.',
    'server_price'=>'Price is calculated by the server','date_and_time'=>'2. Date and time','date'=>'Date','nearby'=>'Nearest available slots','nearby_help'=>'Choose one of the first suitable options immediately.','slots'=>'Available times on the selected date','loading'=>'Checking schedules, rooms and occupied times…','choose_parameters'=>'Choose a service, specialist and date first.','no_slots'=>'No times are available on this date.','to'=>'to',
    'client'=>'3. Customer details','find_client'=>'Find an existing customer','client_search_placeholder'=>'Name, email or phone','search_hint'=>'Enter at least 2 characters.','new_client'=>'New customer','account'=>'Customer','guest'=>'Guest','bookings_count'=>':count appointments','name'=>'First name','lastname'=>'Last name (optional)','phone'=>'Phone','email'=>'Email (optional)','note'=>'Note','customer_note'=>'Customer note (optional)','note_placeholder'=>'Customer preferences or important information for the specialist','admin_note'=>'Internal administrator note','admin_note_placeholder'=>'For example: customer called, confirm details on arrival','admin_note_help'=>'The customer will not see this note.',
    'summary'=>'Selected appointment','not_selected'=>'No time selected yet','save'=>'Create appointment','saving'=>'Creating appointment…','created'=>'Appointment created successfully','created_count'=>':count appointment(s) created','series_created'=>'Series of :count appointments created','request_failed'=>'Could not load available times. Please try again.','search_failed'=>'Could not search customers.','no_customers'=>'No matches found — enter the new customer details.','validation_failed'=>'Check the appointment details.','assigned_master'=>'Appointment will be assigned to: :name',
    'hold_active'=>'This slot is held for you for another :time.','hold_expired'=>'The hold expired. Choose an available slot again.','hold_conflict'=>'This slot was just taken. Refreshing availability.','hold_invalid'=>'The selected interval cannot be held.',
    'duplicate_title'=>'This customer may already exist','duplicate_help'=>'Check the match and select the existing record to avoid a duplicate.','duplicate_email'=>'same email','duplicate_phone'=>'same phone','duplicate_name'=>'same name','use_customer'=>'Select',
    'repeat_booking'=>'Create recurring appointments','repeat_help'=>'Repeat the selected time at the chosen interval. The entire series is validated and created atomically.','repeat_count'=>'Count','repeat_interval'=>'Interval','weeks'=>'{1} :count week|[2,*] :count weeks','occurrences'=>':count appointments in the series','repeated_from'=>'Details copied from appointment #:id. Choose a new available time.','series_conflict'=>'Could not create the series: :date — :message',
    'errors'=>['master'=>'Choose a specialist.','master_service'=>'This specialist does not provide the selected service.','customer_access'=>'This customer is not available in your customer list.','same_day'=>'The appointment must start and end on the same day.','unavailable'=>'The selected time is unavailable. Check schedules, breaks, exceptions and other appointments.','room_unavailable'=>'No room is available at this time. Choose another time.'],
];
