<?php
return [
    'add_new'=>'Add a new appointment',
    'personal_calendar'=>'personal calendar','no_personal_appointments'=>'This employee has no appointments yet. The calendar below shows their personal schedule.','close'=>'Close','select_service'=>'Select a service','select_employee'=>'Select an employee','surname'=>'Last name','appointment_note'=>'Appointment note','save'=>'Save','phone'=>'Phone',
    'all'=>'All appointments','search'=>'Search client, phone, email...','all_employees'=>'All employees','all_services'=>'All services','from'=>'From','to'=>'To','client'=>'Client','service'=>'Service','employee'=>'Employee','date_time'=>'Date and time','price'=>'Price','notes'=>'Notes','action'=>'Action','minutes'=>':count min.','from_price'=>'from','not_found'=>'No appointments found','appointments'=>'Appointments','service_employee'=>'Service / Employee','appointment_time'=>'Appointment time','start'=>'Start','end'=>'End','view_all'=>'View all','view_less'=>'View less','today_title'=>'My appointments today','new'=>'New appointment','result_needed'=>'A result must be recorded.','unresolved_count'=>'Finished appointments without a final status: :count.','past'=>'finished','in_progress'=>'in progress','future'=>'upcoming','status_needed'=>'status needed','until'=>'until :time','details'=>'Details','result_hint'=>'The service ended at :time. Mark it “Completed” or “Client did not attend”.','none_today'=>'No appointments today','none_today_hint'=>'New appointments will appear here automatically.','back_all'=>'← All appointments','appointment_number'=>'Appointment #:id','details_title'=>'Appointment details','employee_label'=>'Employee','cost'=>'Price','room'=>'Room','not_assigned'=>'Not assigned','comment'=>'Comment','no_comment'=>'No comment','about_client'=>'About client','has_account'=>'Has account','guest'=>'Guest','snapshot_hint'=>'Contact details are stored as an appointment snapshot and do not change with the client profile.','recent_client_appointments'=>'Recent client appointments','open'=>'Open','no_other'=>'No other appointments found.','message_client'=>'Message client','subject'=>'Subject','default_subject'=>'Your appointment on :date','message'=>'Message','recipient'=>'Recipient: :email','send_email'=>'Send email','no_email'=>'The client has no email address.','email_sent'=>'Email sent to client','email_subject'=>'Email subject','empty'=>'No history yet.','recent_client_activity'=>'Recent client activity','actions_empty'=>'No activity yet.','cancel_prompt'=>'Enter a cancellation reason','cancel_failed'=>'Could not cancel appointment.',
    'cancel' => 'Cancel appointment', 'cancel_reason' => 'Cancellation reason', 'cancel_reason_help' => 'The reason will be stored in the appointment history.',
    'cancel_confirm' => 'Cancel this appointment on behalf of the business?', 'cancelled' => 'The appointment was cancelled. Its data and history were preserved.',
    'reason_required' => 'Enter a cancellation reason (at least 3 characters).',
    'history' => 'Appointment history', 'system' => 'System', 'reason' => 'Reason', 'empty_history' => 'There is no change history yet.',
    'events' => ['history_started' => 'History tracking started', 'created' => 'Appointment created', 'updated' => 'Appointment updated', 'status_changed' => 'Status changed', 'reschedule_requested' => 'Customer requested rescheduling', 'reschedule_approved' => 'Rescheduling approved', 'reschedule_rejected' => 'Rescheduling rejected'],
    'fields' => ['status' => 'Status', 'service_id' => 'Service', 'user_id' => 'Master', 'room_id' => 'Room', 'appointment_start' => 'Starts', 'appointment_end' => 'Ends', 'price' => 'Price', 'original_price' => 'Original price', 'discount_amount' => 'Discount', 'promo_code' => 'Promo code', 'description' => 'Note'],
    'shown' => 'Showing :from–:to of :total', 'masters_today' => 'Employee appointments', 'today' => 'Today', 'tomorrow' => 'Tomorrow', 'yesterday' => 'Yesterday', 'day_unavailable' => 'Day unavailable', 'non_working_day' => 'Non-working day', 'no_appointments' => 'No appointments', 'calendar' => 'Calendar', 'list' => 'Appointments', 'count' => ':count appointments', 'minutes_short' => ':count min.', 'closed_slot_hint' => 'This date is unavailable for booking. Edit the closed window in settings.', 'image_alt' => 'Image', 'delete_log_error' => 'Error deleting event:', 'time_changed' => 'The time for this date has changed', 'future_rule' => 'From :date the service changes to :duration min., :price €', 'select_service_prompt' => 'Please select a service',
    'change_event' => 'Edit appointment',
];
