<div class="row g-3">
  <div class="col-12"><label class="form-label" for="{{ $prefix }}_type">{{ __('admin_staff.closure_type') }}</label><select class="form-select" id="{{ $prefix }}_type" name="type" required>@foreach(\App\Models\RedDay::typeOptions() as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></div>
  <div class="col-12"><label class="form-label" for="{{ $prefix }}_name">{{ __('admin_staff.closure_name') }}</label><input class="form-control" id="{{ $prefix }}_name" name="name" required maxlength="190" placeholder="{{ __('admin_staff.closure_example') }}"></div>
  <div class="col-12"><label class="form-label" for="{{ $prefix }}_description">{{ __('admin_staff.description') }}</label><textarea class="form-control" id="{{ $prefix }}_description" name="description" maxlength="500" rows="2"></textarea></div>
  <div class="col-6"><label class="form-label" for="{{ $prefix }}_date">{{ __('admin_staff.date_from') }}</label><input class="form-control" id="{{ $prefix }}_date" name="date" type="date" required></div>
  <div class="col-6"><label class="form-label" for="{{ $prefix }}_date_to">{{ __('admin_staff.date_to') }}</label><input class="form-control" id="{{ $prefix }}_date_to" name="date_to" type="date"></div>
  <div class="col-12"><div class="form-check"><input type="hidden" name="full_day" value="0"><input class="form-check-input" id="{{ $prefix }}_full_day" name="full_day" type="checkbox" value="1" checked><label class="form-check-label" for="{{ $prefix }}_full_day">{{ __('admin_staff.full_day') }}</label></div></div>
  <div class="col-6"><label class="form-label" for="{{ $prefix }}_start_time">{{ __('admin_staff.start') }}</label><input class="form-control {{ $prefix }}-time" id="{{ $prefix }}_start_time" name="start_time" type="time"></div>
  <div class="col-6"><label class="form-label" for="{{ $prefix }}_end_time">{{ __('admin_staff.end') }}</label><input class="form-control {{ $prefix }}-time" id="{{ $prefix }}_end_time" name="end_time" type="time"></div>
  <div class="col-12"><div class="form-check"><input type="hidden" name="repeat" value="0"><input class="form-check-input" id="{{ $prefix }}_repeat" name="repeat" type="checkbox" value="1"><label class="form-check-label" for="{{ $prefix }}_repeat">{{ __('admin_staff.repeat_yearly') }}</label></div></div>
</div>
