@section('title', __('crm.settings'))
<x-dashboard-layout>
<div class="content">
  <div class="mb-4"><h2 class="mb-1">{{ __('crm.settings') }}</h2><p class="text-body-tertiary mb-0">{{ __('crm.assignment_hint') }}</p></div>
  <form method="POST" action="{{ route('crm.settings.update') }}" class="card mb-4"><div class="card-body p-4">@csrf @method('PUT')
    <h4 class="mb-4">{{ __('crm.widget') }}</h4>
    <input type="hidden" name="enabled" value="0"><label class="form-check form-switch mb-4"><input class="form-check-input" type="checkbox" name="enabled" value="1" @checked(old('enabled',$settings['enabled']))><span class="form-check-label fw-semibold">{{ __('crm.widget_enabled') }}</span></label>
    <div class="border rounded-3 p-3 mb-4">
      <input type="hidden" name="notify_client_staff_events" value="0">
      <label class="form-check form-switch mb-1">
        <input class="form-check-input" type="checkbox" name="notify_client_staff_events" value="1" @checked(old('notify_client_staff_events',$settings['notify_client_staff_events']))>
        <span class="form-check-label fw-semibold">{{ __('crm.notify_client_staff_events') }}</span>
      </label>
      <p class="text-body-tertiary small mb-0">{{ __('crm.notify_client_staff_events_hint') }}</p>
    </div>
    <div class="row g-3 mb-4"><div class="col-md-6"><label class="form-label">{{ __('crm.timezone') }}</label><input class="form-control" name="timezone" required value="{{ old('timezone',$settings['timezone']) }}"></div></div>
    <div class="border rounded-3 p-3 p-lg-4">
      <div class="d-flex flex-column flex-md-row justify-content-between gap-2 mb-3"><div><h5 class="mb-1">{{ __('crm.widget_messages') }}</h5><p class="text-body-tertiary small mb-0">{{ __('crm.widget_messages_hint') }}</p></div><span class="badge badge-phoenix badge-phoenix-primary align-self-start">{{ __('crm.default_language') }}: {{ strtoupper($defaultSiteLocale) }}</span></div>
      <ul class="nav nav-pills gap-2 mb-3" role="tablist">@foreach($siteLocales as $locale)<li class="nav-item"><button class="nav-link {{ $loop->first ? 'active' : '' }}" data-bs-toggle="pill" data-bs-target="#crm-widget-locale-{{ $locale->code }}" type="button">{{ $locale->native_name }} @unless($locale->enabled)<span class="opacity-50">({{ __('crm.language_disabled') }})</span>@endunless</button></li>@endforeach</ul>
      <div class="tab-content">@foreach($siteLocales as $locale)@php($code=$locale->code)<div class="tab-pane fade {{ $loop->first ? 'show active' : '' }}" id="crm-widget-locale-{{ $code }}"><div class="row g-3">
        <div class="col-12"><label class="form-label">{{ __('crm.widget_title') }}</label><input class="form-control" name="title[{{ $code }}]" maxlength="100" @required($code===$defaultSiteLocale) value="{{ old('title.'.$code,$settings['title_translations'][$code] ?? $settings['title_translations'][$defaultSiteLocale] ?? '') }}"></div>
        <div class="col-md-6"><label class="form-label">{{ __('crm.welcome_message') }}</label><textarea class="form-control" name="welcome_message[{{ $code }}]" rows="3" maxlength="1000" @required($code===$defaultSiteLocale)>{{ old('welcome_message.'.$code,$settings['welcome_message_translations'][$code] ?? $settings['welcome_message_translations'][$defaultSiteLocale] ?? '') }}</textarea></div>
        <div class="col-md-6"><label class="form-label">{{ __('crm.offline_message') }}</label><textarea class="form-control" name="offline_message[{{ $code }}]" rows="3" maxlength="1000" @required($code===$defaultSiteLocale)>{{ old('offline_message.'.$code,$settings['offline_message_translations'][$code] ?? $settings['offline_message_translations'][$defaultSiteLocale] ?? '') }}</textarea></div>
      </div></div>@endforeach</div>
    </div>
    <h5 class="mt-5 mb-3">{{ __('crm.working_hours') }}</h5><div class="table-responsive"><table class="table align-middle"><tbody>@foreach(['monday','tuesday','wednesday','thursday','friday','saturday','sunday'] as $day)@php($hours=$settings['schedule'][$day]??['enabled'=>false,'start'=>'09:00','end'=>'17:00'])<tr><td class="fw-semibold text-capitalize" style="width:12rem">{{ __('admin_schedule.days.'.$day) }}</td><td><input type="hidden" name="schedule[{{ $day }}][enabled]" value="0"><label class="form-check mb-0"><input class="form-check-input" type="checkbox" name="schedule[{{ $day }}][enabled]" value="1" @checked(old("schedule.$day.enabled",$hours['enabled']??false))><span class="form-check-label">{{ __('crm.enabled') }}</span></label></td><td><input class="form-control" type="time" name="schedule[{{ $day }}][start]" value="{{ old("schedule.$day.start",$hours['start']??'09:00') }}" required></td><td><input class="form-control" type="time" name="schedule[{{ $day }}][end]" value="{{ old("schedule.$day.end",$hours['end']??'17:00') }}" required></td></tr>@endforeach</tbody></table></div>
    <h5 class="mt-5 mb-2">{{ __('crm.staff_access') }}</h5><p class="text-body-tertiary">{{ __('crm.assignment_hint') }}</p><div class="table-responsive"><table class="table align-middle"><thead><tr><th>{{ __('admin_nav.staff') }}</th><th>{{ __('crm.staff_enabled') }}</th><th>{{ __('crm.can_view_history') }}</th><th>{{ __('crm.must_answer') }}</th></tr></thead><tbody>@foreach($staff as $index=>$member)@php($chat=$member->chatSettings)<tr><td><input type="hidden" name="staff[{{ $index }}][user_id]" value="{{ $member->id }}"><div class="d-flex align-items-center gap-2"><x-ui.avatar :user="$member" :size="36" /><strong>{{ $member->name }}</strong></div></td>@foreach(['is_enabled'=>'staff_enabled','can_view_history'=>'can_view_history','must_answer'=>'must_answer'] as $field=>$label)<td><input type="hidden" name="staff[{{ $index }}][{{ $field }}]" value="0"><input class="form-check-input" type="checkbox" name="staff[{{ $index }}][{{ $field }}]" value="1" @checked(old("staff.$index.$field",(bool)($chat?->{$field}))) aria-label="{{ __('crm.'.$label) }}"></td>@endforeach</tr>@endforeach</tbody></table></div>
    <div class="text-end mt-4"><button class="btn btn-primary" type="submit">{{ __('crm.save') }}</button></div>
  </div></form>

  <section class="card"><div class="card-body p-4"><h4 class="mb-4">{{ __('crm.tags_settings') }}</h4><form method="POST" action="{{ route('crm.tags.store') }}" class="row g-3 align-items-end mb-4">@csrf<div class="col-md-7"><label class="form-label">{{ __('crm.tag_name') }}</label><input class="form-control" name="name" maxlength="80" required></div><div class="col-md-2"><label class="form-label">{{ __('crm.tag_color') }}</label><input class="form-control form-control-color w-100" type="color" name="color" value="#3874ff" required></div><div class="col-md-3"><button class="btn btn-primary w-100" type="submit">{{ __('crm.add_tag') }}</button></div></form><div class="d-grid gap-2">@foreach($tags as $tag)<div class="border rounded p-3"><form method="POST" action="{{ route('crm.tags.update',$tag) }}" class="row g-2 align-items-center">@csrf @method('PUT')<div class="col"><input class="form-control" name="name" value="{{ $tag->name }}" required></div><div class="col-auto"><input class="form-control form-control-color" type="color" name="color" value="{{ $tag->color }}"></div><div class="col-auto"><span class="badge badge-phoenix badge-phoenix-secondary">{{ $tag->customers_count }}</span></div><div class="col-auto"><button class="btn btn-sm btn-outline-primary" type="submit">{{ __('crm.save') }}</button></div></form><form method="POST" action="{{ route('crm.tags.destroy',$tag) }}" class="text-end mt-2">@csrf @method('DELETE')<button class="btn btn-sm btn-link text-danger" type="submit">{{ __('crm.delete') }}</button></form></div>@endforeach</div></div></section>
  <x-dashboard-footer />
</div>
</x-dashboard-layout>
