@php($prefix = $promo ? 'edit_'.$promo->id.'_' : 'new_')
<div class="row g-3">
  <div class="col-md-4"><label class="form-label" for="{{ $prefix }}code">{{ __('promo.code') }}</label><input class="form-control text-uppercase" id="{{ $prefix }}code" name="code" value="{{ old('code', $promo?->code) }}" maxlength="50" pattern="[A-Za-z0-9_-]+" required></div>
  <div class="col-md-4"><label class="form-label" for="{{ $prefix }}type">{{ __('promo.discount_type') }}</label><select class="form-select" id="{{ $prefix }}type" name="discount_type" required><option value="percentage" @selected(old('discount_type', $promo?->discount_type) === 'percentage')>{{ __('promo.percentage') }}</option><option value="fixed" @selected(old('discount_type', $promo?->discount_type) === 'fixed')>{{ __('promo.fixed') }}</option></select></div>
  <div class="col-md-4"><label class="form-label" for="{{ $prefix }}value">{{ __('promo.discount_value') }}</label><input class="form-control" id="{{ $prefix }}value" name="discount_value" type="number" min="0.01" max="999999" step="0.01" value="{{ old('discount_value', $promo?->discount_value) }}" required></div>
  <div class="col-md-4"><label class="form-label" for="{{ $prefix }}minimum">{{ __('promo.minimum_amount') }}</label><input class="form-control" id="{{ $prefix }}minimum" name="minimum_amount" type="number" min="0" step="0.01" value="{{ old('minimum_amount', $promo?->minimum_amount) }}"></div>
  <div class="col-md-4"><label class="form-label" for="{{ $prefix }}from">{{ __('promo.valid_from') }}</label><input class="form-control" id="{{ $prefix }}from" name="valid_from" type="datetime-local" value="{{ old('valid_from', $promo?->valid_from?->format('Y-m-d\TH:i')) }}"></div>
  <div class="col-md-4"><label class="form-label" for="{{ $prefix }}until">{{ __('promo.valid_until') }}</label><input class="form-control" id="{{ $prefix }}until" name="valid_until" type="datetime-local" value="{{ old('valid_until', $promo?->valid_until?->format('Y-m-d\TH:i')) }}"></div>
  <div class="col-md-4"><label class="form-label" for="{{ $prefix }}limit">{{ __('promo.usage_limit') }}</label><input class="form-control" id="{{ $prefix }}limit" name="usage_limit" type="number" min="1" value="{{ old('usage_limit', $promo?->usage_limit) }}"></div>
  <div class="col-md-4"><label class="form-label" for="{{ $prefix }}customer_limit">{{ __('promo.per_customer_limit') }}</label><input class="form-control" id="{{ $prefix }}customer_limit" name="per_customer_limit" type="number" min="1" value="{{ old('per_customer_limit', $promo?->per_customer_limit) }}"></div>
  <div class="col-md-4"><label class="form-label" for="{{ $prefix }}services">{{ __('promo.services') }}</label><select class="form-select" id="{{ $prefix }}services" name="services[]" multiple size="4">@foreach($services as $service)<option value="{{ $service->id }}" @selected(in_array($service->id, old('services', $promo?->services()->pluck('services.id')->all() ?? [])))>{{ $service->name }}</option>@endforeach</select><div class="form-text">{{ __('promo.all_services_help') }}</div></div>
  <div class="col-md-4"><input type="hidden" name="first_booking_only" value="0"><div class="form-check form-switch mt-4"><input class="form-check-input" id="{{ $prefix }}first" name="first_booking_only" type="checkbox" value="1" @checked(old('first_booking_only', $promo?->first_booking_only ?? false))><label class="form-check-label" for="{{ $prefix }}first">{{ __('promo.first_booking_only') }}</label></div></div>
  <div class="col-md-4"><input type="hidden" name="active" value="0"><div class="form-check form-switch mt-4"><input class="form-check-input" id="{{ $prefix }}active" name="active" type="checkbox" value="1" @checked(old('active', $promo?->active ?? true))><label class="form-check-label" for="{{ $prefix }}active">{{ __('promo.active') }}</label></div></div>
</div>
