<?php
return [
    'add_new'=>'Lisa uus broneering',
    'personal_calendar'=>'isiklik kalender','no_personal_appointments'=>'Sellel töötajal pole veel broneeringuid. Allolev kalender näitab tema isiklikku graafikut.','close'=>'Sulge','select_service'=>'Valige teenus','select_employee'=>'Valige töötaja','surname'=>'Perekonnanimi','appointment_note'=>'Broneeringu märkus','save'=>'Salvesta','phone'=>'Telefon',
    'all'=>'Kõik broneeringud','search'=>'Otsi klienti, telefoni või e-posti...','all_employees'=>'Kõik töötajad','all_services'=>'Kõik teenused','from'=>'Alates','to'=>'Kuni','client'=>'Klient','service'=>'Teenus','employee'=>'Töötaja','date_time'=>'Kuupäev ja kellaaeg','price'=>'Hind','notes'=>'Märkmed','action'=>'Toiming','minutes'=>':count min.','from_price'=>'alates','not_found'=>'Broneeringuid ei leitud','appointments'=>'Broneeringud','service_employee'=>'Teenus / Töötaja','appointment_time'=>'Broneeringu aeg','start'=>'Algus','end'=>'Lõpp','view_all'=>'Näita kõiki','view_less'=>'Näita vähem','today_title'=>'Minu tänased broneeringud','new'=>'Uus broneering','result_needed'=>'Tulemus tuleb märkida.','unresolved_count'=>'Lõppenud broneeringuid ilma lõpliku olekuta: :count.','past'=>'lõppenud','in_progress'=>'praegu käib','future'=>'tulevane','status_needed'=>'olek puudub','until'=>'kuni :time','details'=>'Üksikasjad','result_hint'=>'Teenus lõppes kell :time. Märkige „Lõpetatud” või „Klient ei ilmunud”.','none_today'=>'Täna broneeringuid pole','none_today_hint'=>'Uued broneeringud ilmuvad siia automaatselt.','back_all'=>'← Kõik broneeringud','appointment_number'=>'Broneering #:id','details_title'=>'Broneeringu üksikasjad','employee_label'=>'Töötaja','cost'=>'Maksumus','room'=>'Kabinet','not_assigned'=>'Määramata','comment'=>'Kommentaar','no_comment'=>'Kommentaari pole','about_client'=>'Kliendist','has_account'=>'Kontoga','guest'=>'Külaline','snapshot_hint'=>'Kontaktandmed salvestatakse broneeringu hetktõmmisena ega muutu koos kliendiprofiiliga.','recent_client_appointments'=>'Kliendi viimased broneeringud','open'=>'Ava','no_other'=>'Muid broneeringuid ei leitud.','message_client'=>'Kirjuta kliendile','subject'=>'Teema','default_subject'=>'Teie broneering :date','message'=>'Sõnum','recipient'=>'Saaja: :email','send_email'=>'Saada e-kiri','no_email'=>'Kliendil pole e-posti aadressi.','email_sent'=>'Kliendile saadeti e-kiri','email_subject'=>'Kirja teema','empty'=>'Ajalugu on tühi.','recent_client_activity'=>'Kliendi viimased toimingud','actions_empty'=>'Toiminguid pole.','cancel_prompt'=>'Sisestage tühistamise põhjus','cancel_failed'=>'Broneeringu tühistamine ebaõnnestus.',
    'cancel' => 'Tühista broneering', 'cancel_reason' => 'Tühistamise põhjus', 'cancel_reason_help' => 'Põhjus salvestatakse broneeringu ajalukku.',
    'cancel_confirm' => 'Kas tühistada broneering ettevõtte nimel?', 'cancelled' => 'Broneering tühistati. Andmed ja ajalugu säilitati.',
    'reason_required' => 'Sisestage tühistamise põhjus (vähemalt 3 märki).',
    'history' => 'Broneeringu ajalugu', 'system' => 'Süsteem', 'reason' => 'Põhjus', 'empty_history' => 'Muudatuste ajalugu on veel tühi.',
    'events' => ['history_started' => 'Ajaloo jälgimine alustatud', 'created' => 'Broneering loodud', 'updated' => 'Broneering muudetud', 'status_changed' => 'Olek muudetud', 'reschedule_requested' => 'Klient taotles aja muutmist', 'reschedule_approved' => 'Aja muutmine kinnitatud', 'reschedule_rejected' => 'Aja muutmine tagasi lükatud'],
    'fields' => ['status' => 'Olek', 'service_id' => 'Teenus', 'user_id' => 'Meister', 'room_id' => 'Kabinet', 'appointment_start' => 'Algus', 'appointment_end' => 'Lõpp', 'price' => 'Hind', 'original_price' => 'Alghind', 'discount_amount' => 'Soodustus', 'promo_code' => 'Sooduskood', 'description' => 'Märkus'],
    'shown' => 'Kuvatud :from–:to kokku :total', 'masters_today' => 'Töötajate broneeringud', 'today' => 'Täna', 'tomorrow' => 'Homme', 'yesterday' => 'Eile', 'day_unavailable' => 'Päev pole saadaval', 'non_working_day' => 'Puhkepäev', 'no_appointments' => 'Broneeringuid pole', 'calendar' => 'Kalender', 'list' => 'Broneeringud', 'count' => ':count broneeringut', 'minutes_short' => ':count min.', 'closed_slot_hint' => 'Sellele kuupäevale ei saa broneerida. Muutke suletud aega seadetes.', 'image_alt' => 'Pilt', 'delete_log_error' => 'Sündmuse kustutamise viga:', 'time_changed' => 'Selle kuupäeva aeg on muutunud', 'future_rule' => 'Alates :date muutub teenus: :duration min., :price €', 'select_service_prompt' => 'Palun valige teenus',
    'change_event' => 'Muuda broneeringut',
];
