<?php

return [
    'title'=>'Uus broneering','subtitle'=>'Leia klient ja vaba aeg kiiresti — kõiki piiranguid kontrollib server.','back'=>'Tagasi kalendrisse',
    'service_and_master'=>'1. Teenus ja spetsialist','service'=>'Teenus','choose_service'=>'Vali teenus','master'=>'Spetsialist','any_master'=>'Ükskõik milline vaba spetsialist','any_master_help'=>'Süsteem näitab kõigi spetsialistide lähimaid aegu ja määrab valitud spetsialisti.','current_master'=>'Teie','duration'=>':minutes min',
    'server_price'=>'Hinna arvutab server','date_and_time'=>'2. Kuupäev ja kellaaeg','date'=>'Kuupäev','nearby'=>'Lähimad vabad ajad','nearby_help'=>'Saad kohe valida ühe esimestest sobivatest aegadest.','slots'=>'Valitud kuupäeva vabad ajad','loading'=>'Kontrollime graafikuid, ruume ja hõivatud aegu…','choose_parameters'=>'Vali esmalt teenus, spetsialist ja kuupäev.','no_slots'=>'Sellel kuupäeval pole vabu aegu.','to'=>'kuni',
    'client'=>'3. Kliendi andmed','find_client'=>'Leia olemasolev klient','client_search_placeholder'=>'Nimi, email või telefon','search_hint'=>'Sisesta vähemalt 2 märki.','new_client'=>'Uus klient','account'=>'Klient','guest'=>'Külaline','bookings_count'=>':count broneeringut','name'=>'Eesnimi','lastname'=>'Perekonnanimi (valikuline)','phone'=>'Telefon','email'=>'Email (valikuline)','note'=>'Märkus','customer_note'=>'Kliendi märkus (valikuline)','note_placeholder'=>'Kliendi soovid või spetsialistile oluline teave','admin_note'=>'Administraatori sisemine märkus','admin_note_placeholder'=>'Näiteks: klient helistas, kinnita saabumisel üksikasjad','admin_note_help'=>'Klient seda märkust ei näe.',
    'summary'=>'Valitud broneering','not_selected'=>'Aega pole veel valitud','save'=>'Loo broneering','saving'=>'Loome broneeringut…','created'=>'Broneering on loodud','created_count'=>'Loodi :count broneeringut','series_created'=>'Loodi :count broneeringuga sari','request_failed'=>'Vabu aegu ei õnnestunud laadida. Proovi uuesti.','search_failed'=>'Klientide otsing ebaõnnestus.','no_customers'=>'Vasteid ei leitud — sisesta uue kliendi andmed.','validation_failed'=>'Kontrolli broneeringu andmeid.','assigned_master'=>'Broneering määratakse spetsialistile: :name',
    'hold_active'=>'See aeg on sulle hoitud veel :time.','hold_expired'=>'Aja hoidmine aegus. Vali vaba aeg uuesti.','hold_conflict'=>'See aeg võeti just ära. Uuendame vabu aegu.','hold_invalid'=>'Valitud ajavahemikku ei saa hoida.',
    'duplicate_title'=>'Selline klient võib juba olemas olla','duplicate_help'=>'Kontrolli vastet ja vali olemasolev kaart, et vältida duplikaati.','duplicate_email'=>'sama email','duplicate_phone'=>'sama telefon','duplicate_name'=>'sama nimi','use_customer'=>'Vali',
    'repeat_booking'=>'Loo korduvate broneeringute sari','repeat_help'=>'Korda valitud aega määratud intervalliga. Kogu sari kontrollitakse ja luuakse tervikuna.','repeat_count'=>'Arv','repeat_interval'=>'Intervall','weeks'=>'{1} :count nädal|[2,*] :count nädalat','occurrences'=>'Sarjas on :count broneeringut','repeated_from'=>'Andmed kopeeriti broneeringust #:id. Vali uus vaba aeg.','series_conflict'=>'Sarja ei saanud luua: :date — :message',
    'errors'=>['master'=>'Vali spetsialist.','master_service'=>'See spetsialist ei paku valitud teenust.','customer_access'=>'See klient pole sinu kliendibaasis saadaval.','same_day'=>'Broneering peab algama ja lõppema samal päeval.','unavailable'=>'Valitud aeg pole saadaval. Kontrolli graafikut, pause, erandeid ja teisi broneeringuid.','room_unavailable'=>'Selleks ajaks pole vaba ruumi. Vali teine aeg.'],
];
