@section('title', __('admin_customers.title'))
<x-dashboard-layout>
<div class="content">
  <div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4">
    <div><h2 class="mb-1">{{ __('admin_customers.title') }}</h2><p class="text-body-tertiary mb-0">{{ __('admin_customers.subtitle') }}</p></div>
    <span class="badge badge-phoenix badge-phoenix-primary fs-9">{{ __('admin_customers.found',['count'=>$customers->total()]) }}</span>
  </div>
  <form method="GET" action="{{ route('admin.customers.index') }}" class="card card-body mb-4"><div class="row g-3 align-items-end">
    <div class="col-12 col-lg-5"><label class="form-label" for="customer-search">{{ __('admin_customers.search') }}</label><input id="customer-search" class="form-control" type="search" name="search" maxlength="100" value="{{ request('search') }}" autocomplete="off"></div>
    @if(auth()->user()->role_id === 1)<div class="col-12 col-sm-6 col-lg-3"><label class="form-label" for="customer-master">{{ __('admin_customers.masters') }}</label><select id="customer-master" class="form-select" name="master_id"><option value="">{{ __('admin_customers.all_masters') }}</option>@foreach($masters as $master)<option value="{{ $master->id }}" @selected((string)$masterId===(string)$master->id)>{{ $master->name }}</option>@endforeach</select></div>@endif
    <div class="col-12 col-sm-6 col-lg-2"><label class="form-label" for="customer-sort">{{ __('admin_customers.sort') }}</label><select id="customer-sort" class="form-select" name="sort"><option value="recent" @selected(request('sort','recent')==='recent')>{{ __('admin_customers.recent') }}</option><option value="name" @selected(request('sort')==='name')>{{ __('admin_customers.name') }}</option><option value="appointments" @selected(request('sort')==='appointments')>{{ __('admin_customers.appointments') }}</option></select></div>
    <div class="col-12 col-lg-2 d-flex gap-2"><button class="btn btn-primary flex-grow-1" type="submit">{{ __('admin_customers.find') }}</button><a class="btn btn-outline-secondary" href="{{ route('admin.customers.index') }}" aria-label="{{ __('admin_customers.reset') }}"><span class="fas fa-rotate-left"></span></a></div>
  </div></form>
  <div class="card overflow-hidden"><div class="table-responsive"><table class="table table-hover align-middle mb-0" style="min-width:980px">
    <thead><tr><th class="ps-4">{{ __('admin_customers.client') }}</th><th>{{ __('admin_customers.contacts') }}</th><th>{{ __('admin_customers.masters') }}</th><th>{{ __('admin_customers.statistics') }}</th><th>{{ __('admin_customers.last_visit') }}</th><th></th></tr></thead><tbody>
    @forelse($customers as $customer)<tr data-customer-id="{{ $customer->id }}">
      <td class="ps-4"><div class="d-flex align-items-center gap-3"><x-ui.avatar :name="$customer->full_name" :size="44" /><div class="min-w-0"><a class="fw-bold text-body-emphasis text-break text-decoration-none" href="{{ route('admin.customers.show', $customer) }}">{{ $customer->full_name }}</a><div><span class="badge badge-phoenix badge-phoenix-{{ $customer->has_account ? 'success':'secondary' }} fs-10">{{ $customer->has_account ? __('admin_customers.account'):__('admin_customers.guest') }}</span></div></div></div></td>
      <td><div class="d-grid gap-1"><a class="text-break" href="mailto:{{ $customer->email }}">{{ $customer->email }}</a><a class="text-nowrap" href="tel:{{ $customer->phone }}">{{ $customer->phone }}</a></div></td>
      <td><div class="avatar-group avatar-group-dense py-1">@foreach($customer->master_breakdown->take(5) as $relation)<span class="position-relative d-inline-block" title="{{ $relation->user->name }} · {{ trans_choice('admin_customers.booking_count',$relation->appointments_count,['count'=>$relation->appointments_count]) }}" aria-label="{{ $relation->user->name }}"><x-ui.avatar :user="$relation->user" :size="40" class="border border-2 border-body rounded-circle" /><span class="position-absolute badge rounded-pill bg-primary border border-2 border-body p-1" style="right:-4px;bottom:-5px;min-width:20px">{{ $relation->appointments_count }}</span></span>@endforeach @if($customer->master_breakdown->count()>5)<span class="avatar rounded-circle bg-body-secondary d-inline-flex align-items-center justify-content-center fw-bold" style="width:40px;height:40px" title="{{ __('admin_customers.more_masters',['count'=>$customer->master_breakdown->count()-5]) }}">+{{ $customer->master_breakdown->count()-5 }}</span>@endif</div></td>
      <td><div class="d-flex flex-wrap gap-2 fs-9"><span><strong>{{ $customer->appointments_count }}</strong> {{ __('admin_customers.total') }}</span><span class="text-success"><strong>{{ $customer->completed_count }}</strong> {{ __('admin_customers.completed') }}</span><span class="text-danger"><strong>{{ $customer->no_show_count }}</strong> {{ __('admin_customers.no_show') }}</span>@if($customer->upcoming_count)<span class="text-primary"><strong>{{ $customer->upcoming_count }}</strong> {{ __('admin_customers.upcoming') }}</span>@endif</div></td>
      <td class="text-nowrap">{{ $customer->last_appointment_at ? \Carbon\Carbon::parse($customer->last_appointment_at)->format('d.m.Y H:i') : '—' }}</td>
      <td class="text-end pe-4"><div class="d-inline-flex gap-2"><a class="btn btn-sm btn-primary" href="{{ route('admin.customers.show',$customer) }}">{{ __('admin_customers.open_profile') }}</a><a class="btn btn-sm btn-outline-secondary" href="{{ route('calendarList',['customer_id'=>$customer->id]) }}" title="{{ __('admin_customers.open_bookings') }}" aria-label="{{ __('admin_customers.open_bookings') }}"><span class="fas fa-calendar-alt"></span></a></div></td>
    </tr>@empty<tr><td colspan="6" class="text-center text-body-tertiary py-6">{{ __('admin_customers.empty') }}</td></tr>@endforelse
    </tbody>
  </table></div></div>
  @if($customers->hasPages())<div class="mt-3">{{ $customers->onEachSide(1)->links() }}</div>@endif
  <x-dashboard-footer />
</div>
</x-dashboard-layout>
