@section('title', $conversation->customer?->full_name ?? $conversation->visitor_name)
<x-dashboard-layout>
<div class="content">
  <div class="d-flex flex-wrap justify-content-between gap-3 mb-4"><div><a href="{{ route('crm.chat.index') }}" class="text-decoration-none">← {{ __('crm.chat_title') }}</a><h2 class="mt-2 mb-0">{{ $conversation->customer?->full_name ?? $conversation->visitor_name }}</h2></div><span class="badge badge-phoenix badge-phoenix-{{ $conversation->status==='open'?'success':'secondary' }} align-self-center">{{ __('crm.'.($conversation->status==='open'?'open_conversations':'closed_conversations')) }}</span></div>
  <div class="row g-4">
    <aside class="col-12 col-xl-4"><div class="card"><div class="card-body"><h5>{{ __('crm.customer_card') }}</h5><div class="d-grid gap-2 mt-3"><a href="mailto:{{ $conversation->customer?->email ?? $conversation->visitor_email }}">{{ $conversation->customer?->email ?? $conversation->visitor_email ?: '—' }}</a><a href="tel:{{ $conversation->customer?->phone ?? $conversation->visitor_phone }}">{{ $conversation->customer?->phone ?? $conversation->visitor_phone ?: '—' }}</a>@if($conversation->customer && auth()->user()->hasPermission('crm.view'))<a class="btn btn-outline-primary mt-2" href="{{ route('crm.customers.show',$conversation->customer) }}">{{ __('crm.customer_card') }}</a>@endif</div><hr><label class="form-label">{{ __('crm.assigned_to') }}</label><select id="crm-transfer-user" class="form-select"><option value="">{{ __('crm.unassigned') }}</option>@foreach($staff as $member)<option value="{{ $member->id }}" @selected($conversation->assigned_to_user_id===$member->id)>{{ $member->name }}</option>@endforeach</select><button id="crm-transfer" class="btn btn-outline-primary w-100 mt-2" type="button">{{ __('crm.transfer') }}</button>@if($conversation->status==='open')<button id="crm-close" class="btn btn-outline-danger w-100 mt-3" type="button">{{ __('crm.close') }}</button>@endif</div></div></aside>
    <section class="col-12 col-xl-8"><div class="card overflow-hidden"><div id="crm-chat-messages" class="card-body d-flex flex-column gap-3" style="height:min(60vh,38rem);overflow:auto">@foreach($conversation->messages as $message)<div class="d-flex {{ $message->sender_type==='staff'?'justify-content-end':'justify-content-start' }}" data-message-id="{{ $message->id }}"><div class="rounded-3 px-3 py-2 {{ $message->sender_type==='staff'?'bg-primary text-white':($message->sender_type==='system'?'bg-body-secondary':'bg-body-highlight') }}" style="max-width:min(85%,42rem)"><small class="d-block opacity-75">{{ $message->staffSender?->name ?? ($message->sender_type==='staff'?__('admin_nav.staff'):($conversation->customer?->full_name ?? $conversation->visitor_name)) }} · {{ $message->created_at->format('H:i') }}</small><div style="white-space:pre-wrap" class="text-break">{{ $message->body }}</div></div></div>@endforeach</div>@if($conversation->status==='open')<form id="crm-chat-reply" class="card-footer d-flex gap-2"><textarea class="form-control" name="message" rows="2" maxlength="5000" required placeholder="{{ __('crm.write_reply') }}"></textarea><button class="btn btn-primary" type="submit">{{ __('crm.send') }}</button></form>@endif</div></section>
  </div><x-dashboard-footer />
</div>
@push('scripts')
<script>
(() => {
  const csrf = document.querySelector('meta[name="csrf-token"]')?.content;
  const box = document.getElementById('crm-chat-messages');
  let lastId = Number(box?.lastElementChild?.dataset.messageId || 0);
  const request = async (url, options={}) => fetch(url, {credentials:'same-origin',headers:{'Accept':'application/json','Content-Type':'application/json','X-CSRF-TOKEN':csrf,'X-Requested-With':'XMLHttpRequest'},...options});
  const append = message => { if (!box || document.querySelector(`[data-message-id="${message.id}"]`)) return; const row=document.createElement('div'); row.className='d-flex '+(message.sender==='staff'?'justify-content-end':'justify-content-start'); row.dataset.messageId=message.id; const bubble=document.createElement('div'); bubble.className='rounded-3 px-3 py-2 text-break '+(message.sender==='staff'?'bg-primary text-white':message.sender==='system'?'bg-body-secondary':'bg-body-highlight'); bubble.style.maxWidth='min(85%,42rem)'; const meta=document.createElement('small'); meta.className='d-block opacity-75'; meta.textContent=(message.sender_name || (message.sender==='staff'?@js(__('admin_nav.staff')):@js($conversation->customer?->full_name ?? $conversation->visitor_name)))+' · '+new Date(message.time).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}); const body=document.createElement('div'); body.style.whiteSpace='pre-wrap'; body.textContent=message.body; bubble.append(meta,body); row.append(bubble); box.append(row); lastId=Math.max(lastId,Number(message.id)); box.scrollTop=box.scrollHeight; };
  const poll=async()=>{if(document.hidden)return;try{const response=await request(@js(route('crm.chat.messages',$conversation))+'?after='+lastId);if(!response.ok)return;(await response.json()).messages.forEach(append);}catch(_){}};
  document.getElementById('crm-chat-reply')?.addEventListener('submit',async event=>{event.preventDefault();const field=event.currentTarget.elements.message;const body=field.value.trim();if(!body)return;const response=await request(@js(route('crm.chat.reply',$conversation)),{method:'POST',body:JSON.stringify({message:body})});if(response.ok){field.value='';await poll();}});
  document.getElementById('crm-transfer')?.addEventListener('click',async()=>{const userId=document.getElementById('crm-transfer-user').value;if(!userId)return;const response=await request(@js(route('crm.chat.transfer',$conversation)),{method:'POST',body:JSON.stringify({user_id:userId})});if(response.ok)await poll();});
  document.getElementById('crm-close')?.addEventListener('click',async()=>{const response=await request(@js(route('crm.chat.close',$conversation)),{method:'POST',body:'{}'});if(response.ok)location.reload();});
  box.scrollTop=box.scrollHeight; window.setInterval(poll,3000);
})();
</script>
@endpush
</x-dashboard-layout>
