server {
    listen 80;
    server_name localhost;
    root /var/www/public;
    index index.php index.html;
    client_max_body_size 10M;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Алиас: /public/vendors/ -> /var/www/public/vendors/
    location /public/vendors/ {
        alias /var/www/public/vendors/;
    }

    # Алиас: /public/storage/ -> /var/www/public/storage/
    location /public/storage/ {
        alias /var/www/public/storage/;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }
}