@section('title', __('customer.create_account'))
<x-app-layout><section class="py-8 py-lg-10"><div class="container" style="max-width:680px"><div class="card shadow-sm"><div class="card-body p-4 p-md-5">
<h1 class="fs-4 mb-2">{{ __('customer.create_account') }}</h1><p class="text-body-secondary mb-4">{{ __('customer.register_help') }}</p>
<form method="POST" action="{{ route('customer.register.store') }}">@csrf<div class="row g-3">
<div class="col-md-6"><label class="form-label">{{ __('customer.first_name') }}</label><input class="form-control" name="first_name" value="{{ old('first_name') }}" required></div><div class="col-md-6"><label class="form-label">{{ __('customer.last_name') }}</label><input class="form-control" name="last_name" value="{{ old('last_name') }}"></div>
<div class="col-md-6"><label class="form-label">Email</label><input class="form-control @error('email') is-invalid @enderror" name="email" type="email" value="{{ old('email') }}" required>@error('email')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6"><label class="form-label">{{ __('customer.phone') }}</label><input class="form-control @error('phone') is-invalid @enderror" name="phone" value="{{ old('phone') }}" placeholder="+37255555555" required>@error('phone')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="col-md-6"><label class="form-label">{{ __('customer.password') }}</label><input class="form-control" name="password" type="password" required></div><div class="col-md-6"><label class="form-label">{{ __('customer.repeat_password') }}</label><input class="form-control" name="password_confirmation" type="password" required></div>
<div class="col-12"><div class="form-check"><input class="form-check-input" id="terms" name="terms" type="checkbox" value="1" required><label class="form-check-label" for="terms">{{ __('customer.accept_policy') }}: <a href="{{ route('policy') }}" target="_blank">{{ __('customer.privacy_policy') }}</a></label></div></div></div>
@if($errors->any())<div class="alert alert-danger mt-3">{{ __('customer.check_data') }}</div>@endif<button class="btn btn-primary w-100 mt-4" type="submit">{{ __('customer.create_account') }}</button></form>
</div></div></div></section></x-app-layout>
