@section('title', __('customer.reschedule'))
@push('styles')<style>
.reschedule-calendar{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));border:1px solid var(--phoenix-border-color);border-radius:.75rem;overflow:hidden}.reschedule-calendar>*{min-width:0;min-height:48px;border:0;border-right:1px solid var(--phoenix-border-color);border-bottom:1px solid var(--phoenix-border-color);background:transparent}.reschedule-calendar .weekday{min-height:auto;padding:.5rem .2rem;text-align:center;font-weight:600}.reschedule-day.available{color:var(--phoenix-primary);font-weight:700;background:rgba(var(--phoenix-primary-rgb),.06)}.reschedule-day.available:hover,.reschedule-day.selected{background:var(--phoenix-primary);color:var(--brand-accent-contrast)}.reschedule-day.unavailable{text-decoration:line-through;opacity:.35;cursor:not-allowed}.reschedule-day.outside{opacity:.12}
</style>@endpush
<x-app-layout><section class="py-7 py-lg-9"><div class="container" style="max-width:860px">
<h1 class="fs-4">{{ __('customer.reschedule') }}</h1><p>{{ $appointment->service->getTranslation(app()->getLocale(), 'name') ?? $appointment->service->name }} · {{ $appointment->user->name }}</p><p class="text-body-secondary">{{ __('customer.current_time') }}: {{ $appointment->appointment_start->format('d.m.Y H:i') }}</p>
@error('appointment')<div class="alert alert-danger">{{ $message }}</div>@enderror
<form method="POST" action="{{ route('customer.appointments.reschedule.store', ['appointment'=>$appointment->public_uuid]) }}" id="reschedule-form">@csrf
<section class="card card-body mb-4"><h2 class="fs-7">{{ __('customer.recommended_times') }}</h2><div class="d-flex flex-wrap gap-2" id="recommended-slots">@forelse($recommendations as $slot)<button type="button" class="btn btn-outline-primary recommended-slot" data-date="{{ $slot['date'] }}" data-start="{{ $slot['start'] }}" data-end="{{ $slot['end'] }}">{{ Carbon\Carbon::parse($slot['date'])->format('d.m') }} · {{ $slot['start'] }}</button>@empty<span class="text-body-secondary">{{ __('customer.no_times') }}</span>@endforelse</div></section>
<section class="card card-body mb-4"><div class="d-flex justify-content-between align-items-center mb-3"><button class="btn btn-sm btn-outline-secondary" id="calendar-prev" type="button" aria-label="{{ __('pagination.previous') }}">‹</button><h2 class="fs-7 mb-0" id="calendar-title"></h2><button class="btn btn-sm btn-outline-secondary" id="calendar-next" type="button" aria-label="{{ __('pagination.next') }}">›</button></div><div id="reschedule-calendar" class="reschedule-calendar" aria-live="polite"></div></section>
<input id="reschedule-date" name="date" type="hidden"><input type="hidden" name="start" id="reschedule-start"><input type="hidden" name="end" id="reschedule-end">
<section class="card card-body mb-4"><h2 class="fs-7" id="slots-title">{{ __('customer.show_times') }}</h2><div id="reschedule-slots" class="row g-2" aria-live="polite"><span class="text-body-secondary">{{ __('customer.choose_available_day') }}</span></div></section>
<section class="card card-body"><label class="form-label" for="reschedule-reason">{{ __('customer.reschedule_reason') }}</label><textarea class="form-control mb-3" id="reschedule-reason" name="reason" maxlength="500"></textarea><p class="small text-body-secondary">{{ __('customer.reschedule_hold_notice') }}</p><button class="btn btn-primary" type="submit">{{ __('customer.send_reschedule') }}</button></section>
</form></div></section>
@push('scripts')<script>
document.addEventListener('DOMContentLoaded',()=>{
 const locale=@js(app()->getLocale()), calendar=document.getElementById('reschedule-calendar'), title=document.getElementById('calendar-title'), dateInput=document.getElementById('reschedule-date'), startInput=document.getElementById('reschedule-start'), endInput=document.getElementById('reschedule-end'), slotsBox=document.getElementById('reschedule-slots'), limitDate=new Date(@js($limitDate->toDateString())+'T00:00:00');
 let cursor=new Date(), selectedDate=null;
 const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
 async function loadSlots(date,preferred=null){dateInput.value=date;selectedDate=date;startInput.value='';endInput.value='';slotsBox.textContent=@js(__('customer.loading'));const response=await fetch(@js(route('customer.appointments.reschedule.slots',['appointment'=>$appointment->public_uuid])),{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]').content},body:JSON.stringify({date})});const data=await response.json();slotsBox.innerHTML='';(data.slots||[]).forEach((slot,index)=>{const col=document.createElement('div');col.className='col-6 col-sm-4 col-md-3';col.innerHTML=`<input class="btn-check" type="radio" id="slot-${index}" name="slot"><label class="btn btn-outline-primary w-100" for="slot-${index}">${slot.start}</label>`;const radio=col.querySelector('input');radio.addEventListener('change',()=>{startInput.value=slot.start;endInput.value=slot.end});slotsBox.appendChild(col);if(preferred===slot.start){radio.checked=true;radio.dispatchEvent(new Event('change'))}});if(!data.slots?.length)slotsBox.textContent=@js(__('customer.no_times'));document.querySelectorAll('.reschedule-day').forEach(button=>button.classList.toggle('selected',button.dataset.date===date));}
 async function render(){const first=new Date(cursor.getFullYear(),cursor.getMonth(),1),last=new Date(cursor.getFullYear(),cursor.getMonth()+1,0),rangeStart=new Date(first);rangeStart.setDate(first.getDate()-((first.getDay()+6)%7));const rangeEnd=new Date(rangeStart);rangeEnd.setDate(rangeStart.getDate()+41);title.textContent=new Intl.DateTimeFormat(locale,{month:'long',year:'numeric'}).format(first);calendar.innerHTML='';for(let i=0;i<7;i++){const d=new Date(2024,0,1+i),el=document.createElement('div');el.className='weekday';el.textContent=new Intl.DateTimeFormat(locale,{weekday:'short'}).format(d);calendar.appendChild(el)}const response=await fetch(@js(route('customer.appointments.reschedule.days',['appointment'=>$appointment->public_uuid]))+`?start=${iso(rangeStart)}&end=${iso(rangeEnd)}`,{headers:{Accept:'application/json'}});const available=(await response.json()).days||{};for(let i=0;i<42;i++){const d=new Date(rangeStart);d.setDate(rangeStart.getDate()+i);const key=iso(d),button=document.createElement('button');button.type='button';button.textContent=d.getDate();button.dataset.date=key;button.className='reschedule-day '+(d.getMonth()===cursor.getMonth()?'':'outside ')+(available[key]?'available':'unavailable');button.disabled=!available[key];if(available[key])button.addEventListener('click',()=>loadSlots(key));if(key===selectedDate)button.classList.add('selected');calendar.appendChild(button)}document.getElementById('calendar-prev').disabled=first<=new Date(new Date().getFullYear(),new Date().getMonth(),1);document.getElementById('calendar-next').disabled=new Date(cursor.getFullYear(),cursor.getMonth()+1,1)>limitDate;}
 document.getElementById('calendar-prev').addEventListener('click',()=>{cursor.setMonth(cursor.getMonth()-1);render()});document.getElementById('calendar-next').addEventListener('click',()=>{cursor.setMonth(cursor.getMonth()+1);render()});document.querySelectorAll('.recommended-slot').forEach(button=>button.addEventListener('click',()=>{const d=new Date(button.dataset.date+'T00:00:00');cursor=new Date(d.getFullYear(),d.getMonth(),1);render();loadSlots(button.dataset.date,button.dataset.start)}));document.getElementById('reschedule-form').addEventListener('submit',event=>{if(!dateInput.value||!startInput.value){event.preventDefault();slotsBox.textContent=@js(__('customer.choose_time'))}});render();
});
</script>@endpush
</x-app-layout>
